version: '3.8'

services:
  express-app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app:rw,cached
      - ./node_modules:/app/node_modules:rw,cached
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    

  mysql:
    image: mysql:8.2
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: express_db
    ports:
      - "11011:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - "./infra/config/mysql/my.cnf:/etc/mysql/conf.d/zz-my.cnf:ro"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 3s
      timeout: 5s
      retries: 5
    

  adminer:
    image: adminer:5.2.1
    container_name: adminer
    ports:
      - "11012:8080"
    restart: unless-stopped
    depends_on:
      - mysql
    environment: 
      ADMINER_DESIGN: "pepa_linha"
      ADMINER_DEFAULT_SERVER: "mysql"
      ADMINER_DEFAULT_DB: "express_db"
    links:
      - mysql


volumes:
  mysql_data: ~